config/routes.rb
Rails.application.routes.draw do
  
  root to: 'modes#index'
	
  # User Settings
  resources :user_settings

  # Audit Trail
  resources :audit_trail, only: [:index] do
    collection do
      post :search
      get :export_csv
    end
  end

  # Studies
  resources :studies, only: [:index, :destroy, :create] do
    collection do
    	get :new_from_mdr
    	#get :new_from_study
    	get :new_from_define
    end
    member do
      get :history
      #post :build
    end
  end
  
  namespace :studies do
	  resources :bases, only: [:edit, :update] do
      member do
        put :default
        put :terminology_toggle
      end
    end
    resources :forms, except: [:index] do
      member do
        put :move
        get :crf
      end
      collection do
        post :create_local
      end
      resources :normal_groups, only: [] do
        member do
          get :add_bc
        end
      end
    end
    
    resources :variables, only: [:index, :show, :edit] do
      member do
        get :status
        put :toggle
        put :update_comment
        put :remove_comment
        put :update_derivation
        put :remove_derivation
      end
    end
  end

end

app/views/user_settings/index.html.erb
<div class="row">
	<div class="col-md-9">
		<div class="row">
			<div class="col-md-12">
				<div class="panel panel-default">
					<div class="panel-heading">
						<h4 class="panel-title">Current Settings: <%= current_user.name %> (<%= current_user.email %>)</h4>
					</div>
		  		<div class="panel-body">
		    		<div class="row">
							<div class="col-md-6">
								<table id="user_info" class="table table-striped table-condensed">
									<tbody>
										<tr>
											<th class="col-md-4">Display Name:</th><td><%= current_user.name %></td>
										</tr>
										<tr>
											<th>Email:</th><td><%= current_user.email %></td>
										</tr>
									</tbody>
								</table>
							</div>
						</div>
						<div class="row">
							<div class="col-md-12">
								<p>Your current settings are listed below. These may be changed by using the buttons to the right.</p>
								<% ordered_metadata = @settings_metadata.sort_by {|key, x| x[:label]} %>
								<table id="user_settings" class="table table-striped table-condensed">
									<tbody>
										<% ordered_metadata.each do |key, md| %>
											<tr>
									    	<th class="col-md-2"><%= md[:label] %>:</th>
									    	<td class="col-md-6"><%= md[:description] %></td>
									    	<% if md[:type] == "enum" %>
									    		<% md[:values].each do |option| %>
									    			<% if option == @settings[key] %>
									    				<td class="col-md-1">
									    			 		<%= link_to @settings[key], user_setting_path(:id => current_user.id, :user_settings => {:name => key, :value => option}), :method => :put, :class => "btn btn-success btn-xs" %>
									    			 	</td>
									    			<% end %>
									    		<% end %>
									    		<td class="col-md-3">
											  		<% md[:values].each do |option| %>
											  			<% if option != @settings[key] %>
											  			 	<%= link_to option, user_setting_path(:id => current_user.id, :user_settings => {:name => key, :value => option}), :method => :put, :class => "btn btn-primary btn-xs" %>
											  			<% end %>
											  		<% end %>
											  	</td>
									    	<% elsif md[:type] == "coded" %>
									    		<% md[:values].each do |value_key, option| %>
									    			<% if option.to_s == @settings[key] %>
									    				<td class="col-md-1">
									    					<%= link_to value_key, user_setting_path(:id => current_user.id, :user_settings => {:name => key, :value => option}), :method => :put, :class => "btn btn-success btn-xs" %>
									    			 	</td>
									    			<% end %>
									    		<% end %>
		  										<td class="col-md-3">
											  		<% md[:values].each do |value_key, option| %>
											  			<% if option.to_s != @settings[key] %>
											  			 		<%= link_to value_key, user_setting_path(:id => current_user.id, :user_settings => {:name => key, :value => option}), :method => :put, :class => "btn btn-primary btn-xs" %>
											  			<% end %>
											  		<% end %>
		  										</td>
									    	<% end %>
										  </tr>
										<% end %>
									</tbody>
								</table>
							</div>
						</div>
		  		</div>
				</div>
			</div>
		</div>
	</div>
	<div class="col-md-3">
		<div class="row">
			<div class="col-md-12">
				<div class="panel panel-default">
					<div class="panel-heading">
						<h4 class="panel-title">Change Password</h4>
					</div>
		  		<div class="panel-body">
	  			  <%= form_for(current_user, url: registration_path(current_user), html: { method: :put }) do |f| %>
					    <div class="form-group">
					      <%= f.label :current_password, "Current Password:" %>
					      <%= f.password_field :current_password, autocomplete: "off", class: "form-control" %>
					    </div>
					    <div class="form-group">
					      <%= f.label :password, "New Password:" %>
					      <% if @minimum_password_length %>
					        <em>(<%= @minimum_password_length %> characters minimum)</em>
					      <% end %><br />
					      <%= f.password_field :password, autocomplete: "off", class: "form-control" %>
					    </div>
					    <div class="form-group">
					      <%= f.label :password_confirmation, "Confirm New Password:" %>
					      <% if @minimum_password_length %>
					        <em>(<%= @minimum_password_length %> characters minimum)</em>
					      <% end %><br />
					      <%= f.password_field :password_confirmation, autocomplete: "off", class: "form-control" %>
					    </div>
					    <%= f.submit "Update", id: "password_update_button", class: "btn btn-default btn-primary" %>
					  <% end %>
		  		</div>
			  </div>
		  </div>
		</div>
		<div class="row">
			<div class="col-md-12">
				<div class="panel panel-default">
					<div class="panel-heading">
						<h4 class="panel-title">Change Display Name</h4>
					</div>
		  		<div class="panel-body">
	  			  <%= form_for(current_user, url: update_name_user_path(current_user), html: { method: :put }) do |f| %>
					    <div class="form-group">
					      <%= f.label :name, "New Display Name:" %>
					      <%= f.text_field :name, class: "form-control" %>
					    </div>
					    <%= f.submit "Update", id: "name_update_button", class: "btn btn-default btn-primary" %>
					  <% end %>
		  		</div>
			  </div>
		  </div>
		</div>
	</div>
</div>